# Generated by Django 6.1.1 on 2026-09-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_concepts', to='accounts.institution')),
            ],
            options={
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_id', models.CharField(max_length=80)),
                ('gloss', models.CharField(max_length=200)),
                ('language', models.CharField(default='lsb', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signs', to='accounts.institution')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signs', to='vocabulary.signconcept')),
            ],
            options={
                'ordering': ('sign_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConceptAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(editable=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_aliases', to='accounts.institution')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='vocabulary.signconcept')),
            ],
            options={
                'ordering': ('normalized_alias', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SignPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('language', models.CharField(default='lsb', max_length=16)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('non_manual_markers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_plans', to='vocabulary.signconcept')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_plans', to='accounts.institution')),
            ],
            options={
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('hamnosys', models.TextField(blank=True, help_text='Optional opaque notation; not asserted to be an LSB standard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_variants', to='accounts.institution')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='vocabulary.sign')),
            ],
            options={
                'ordering': ('variant_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SignPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sign_plan_items', to='accounts.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vocabulary.signplan')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='vocabulary.sign')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='vocabulary.signvariant')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='signconcept',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='vocab_concept_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='signconcept',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='vocab_concept_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sign',
            constraint=models.UniqueConstraint(fields=('institution', 'sign_id'), name='vocab_sign_id_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='sign',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='vocab_sign_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'validated', 'rejected'])), name='vocab_sign_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='conceptalias',
            constraint=models.UniqueConstraint(fields=('institution', 'normalized_alias'), name='vocab_alias_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='conceptalias',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='vocab_alias_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='signplan',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='vocab_plan_code_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='signplan',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='vocab_plan_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='signplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'validated', 'rejected'])), name='vocab_plan_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='signvariant',
            constraint=models.UniqueConstraint(fields=('sign', 'variant_code'), name='vocab_variant_code_per_sign'),
        ),
        migrations.AddConstraint(
            model_name='signvariant',
            constraint=models.UniqueConstraint(fields=('id', 'institution'), name='vocab_variant_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='signplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='vocab_plan_position_unique'),
        ),
    ]
