# Generated by Django 6.1.1 on 2026-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conceptalias',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_alias', ''), _negated=True), name='vocab_alias_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sign',
            constraint=models.CheckConstraint(condition=models.Q(('sign_id', ''), _negated=True), name='vocab_sign_stable_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='signconcept',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='vocab_concept_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='signplan',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='vocab_plan_code_not_empty'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "vocabulary_sign" ADD CONSTRAINT "vocab_sign_concept_tenant_fk" FOREIGN KEY ("concept_id", "institution_id") REFERENCES "vocabulary_signconcept" ("id", "institution_id") ON DELETE RESTRICT',
                'ALTER TABLE "vocabulary_conceptalias" ADD CONSTRAINT "vocab_alias_concept_tenant_fk" FOREIGN KEY ("concept_id", "institution_id") REFERENCES "vocabulary_signconcept" ("id", "institution_id") ON DELETE RESTRICT',
                'ALTER TABLE "vocabulary_signplan" ADD CONSTRAINT "vocab_plan_concept_tenant_fk" FOREIGN KEY ("concept_id", "institution_id") REFERENCES "vocabulary_signconcept" ("id", "institution_id") ON DELETE RESTRICT',
                'ALTER TABLE "vocabulary_signvariant" ADD CONSTRAINT "vocab_variant_sign_tenant_fk" FOREIGN KEY ("sign_id", "institution_id") REFERENCES "vocabulary_sign" ("id", "institution_id") ON DELETE RESTRICT',
                'ALTER TABLE "vocabulary_signplanitem" ADD CONSTRAINT "vocab_item_plan_tenant_fk" FOREIGN KEY ("plan_id", "institution_id") REFERENCES "vocabulary_signplan" ("id", "institution_id") ON DELETE CASCADE',
                'ALTER TABLE "vocabulary_signplanitem" ADD CONSTRAINT "vocab_item_sign_tenant_fk" FOREIGN KEY ("sign_id", "institution_id") REFERENCES "vocabulary_sign" ("id", "institution_id") ON DELETE RESTRICT',
                'ALTER TABLE "vocabulary_signplanitem" ADD CONSTRAINT "vocab_item_variant_tenant_fk" FOREIGN KEY ("variant_id", "institution_id") REFERENCES "vocabulary_signvariant" ("id", "institution_id") ON DELETE RESTRICT',
            ],
            reverse_sql=[
                'ALTER TABLE "vocabulary_signplanitem" DROP CONSTRAINT "vocab_item_variant_tenant_fk"',
                'ALTER TABLE "vocabulary_signplanitem" DROP CONSTRAINT "vocab_item_sign_tenant_fk"',
                'ALTER TABLE "vocabulary_signplanitem" DROP CONSTRAINT "vocab_item_plan_tenant_fk"',
                'ALTER TABLE "vocabulary_signvariant" DROP CONSTRAINT "vocab_variant_sign_tenant_fk"',
                'ALTER TABLE "vocabulary_signplan" DROP CONSTRAINT "vocab_plan_concept_tenant_fk"',
                'ALTER TABLE "vocabulary_conceptalias" DROP CONSTRAINT "vocab_alias_concept_tenant_fk"',
                'ALTER TABLE "vocabulary_sign" DROP CONSTRAINT "vocab_sign_concept_tenant_fk"',
            ],
        ),
    ]
