# Generated by Django 6.1.1 on 2026-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vocabulary', '0002_conceptalias_vocab_alias_not_empty_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signvariant',
            constraint=models.CheckConstraint(condition=models.Q(('variant_code', ''), _negated=True), name='vocab_variant_code_not_empty'),
        ),
    ]
